### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by Krokit**
Added image table.
Added new post features like published and featured.
Added SoftDelets on Comments and Posts.
Added in every model fillable, casts and dates.

Image Resources will be added in next update, also i will update others resources.

### CODE REVIEW

**Comment by MattMangoni** [comment]
Thanks, I'll check it out as soon as I have time. 

From now on, let's work only in the dev branch :)

**Comment by Krokit** [comment]
Okay i will push new commits to dev. :) i will push the last commit to fix some foolish mistakes. :)

**Comment by Krokit** [comment]
For now can you wait to push and Resources and then merge?

**Comment by MattMangoni** [comment]
Tell me when you're ready :)

**Comment by Krokit** [comment]
I found it. :D

**Comment by Krokit** [comment]
I have more commits to do.

**Comment by MattMangoni** [comment]
It's not a problem, don't worry :)

**Comment by Krokit** [comment]
Okay but next commit will be again in master because right now images are not working well and upcoming commits will be pushed in dev. :)

**Comment by MattMangoni** [comment]
No problem :)

**Pull request merged**
