### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by Krokit**
New navigation

### CODE REVIEW

**Comment by MattMangoni** [comment]
nice job on the navigation part :)

**Comment by Krokit** [comment]
Thanks, i m working now of image field and tags field, but for tags field i will have a lot of works with vuejs and vuejs isn't my friend :D

**Comment by MattMangoni** [comment]
You want to make something like this? https://packagist.org/packages/spatie/nova-tags-field

**Comment by Krokit** [comment]
I will check this package. :) and if it's good one i will "take" it for free 😄

**Comment by MattMangoni** [comment]
I dislike the fact that it uses a json field tho

**Comment by Krokit** [comment]
I can make it with text field, but the design doesn't support tags. I will try to use their code to create smh. :)

**Pull request merged**
