### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Krokit**
Image upload

### CODE REVIEW

**Comment by Krokit** [comment]
@MattMangoni StyleCi wants to play games with me like the film saw. 😄 😄

**Comment by Krokit** [comment]
Ready for Merge. 😄 Check if there is preview image when updating post because my admin panel is under subdomain and crossfire is blocking it. :)

**Comment by MattMangoni** [comment]
Checking it out right now :)
Thanks!

**Comment by Krokit** [comment]
After the merge, I will push new commit with language option.

**Comment by MattMangoni** [comment]
Done :)

**Pull request merged**
