### PR TITLE
New Features.

### PR DESCRIPTION
**Pull request by Krokit**
I'm working on new features. At the moment i need to change the fields in Resource for Tag and Comments. Tomorrow i will upload new files and changes.

### CODE REVIEW

**Comment by MattMangoni** [comment]
Merging, thank you!

**Comment by Krokit** [comment]
@MattMangoni  At the moment i need to change the fields in Resource for Tag and Comments if i want to work. :) Next time checks the code first, before merging.😄 I will upload new files today so users will be able to use Tags and Comments and install page 😄

**Comment by MattMangoni** [comment]
@Krokit I'm doing it right now :)

**Comment by Krokit** [comment]
@MattMangoni  Okay. I will add image upload and i think will be good to add protected $with ['']; a.k.a eager loading on Post model, to load author, tags, comments, and category.

**Comment by MattMangoni** [comment]
@Krokit of course :)
For the time being, I made the Tags resource hidden until a couple of problems are fixed.

I also temporarily changed switched the Trix field with the Markdown one, but this is just until some weird problems are fixed.

**Comment by Krokit** [comment]
@MattMangoni What problems with Tags Resources? Tell soo i can try to help. :)

**Comment by MattMangoni** [comment]
@Krokit looks like there's no problem at all now, should be ok now. The tag feature is now fully functional. 

Thank you for your help :)

**Pull request merged**
